---

- hosts: all
  become: true
  tasks:
  
  - name: update apt index 
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install apache2 package
    apt:
      name: apache2
    
  - name: Install Snap
    apt:
      name: snapd

  - name: Install Microk8s
    snap:
      name: microk8s 
      classic: yes
